<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close</name>
   <tag></tag>
   <elementGuidId>c687d2f9-0940-4fa3-80a4-9dd70408522c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alertdialog-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='alertdialog-close']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6aef5288-7419-4715-b2b4-c4d3b6ca283a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>26c74bc0-8aa8-4171-875b-f60d1adc29c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alertdialog-close</value>
      <webElementGuid>5f6da050-9f59-4791-a5dd-2f8b1ec3e8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-raised-button mat-button-base mat-primary cdk-focused cdk-program-focused</value>
      <webElementGuid>0d2dbd9b-80f2-43a7-b45a-928df9c98e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>fd2453be-1ac0-4181-88cd-b3ee5eedd744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alertdialog-close&quot;)</value>
      <webElementGuid>917adf27-4c22-43f5-842b-9e4bf5b8d4f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='alertdialog-close']</value>
      <webElementGuid>fd3a3c97-2d68-42fe-954b-f900755c3066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/n2-platform-alert-dialog/mat-dialog-content/div/div[2]/div[3]/div/button</value>
      <webElementGuid>2bf5a131-31b7-47a0-86af-b45bb2fbde14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No record found, please change your search criteria.'])[1]/following::button[1]</value>
      <webElementGuid>ce385bb5-d5bb-4813-83b5-14d15b4cedb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info'])[1]/following::button[1]</value>
      <webElementGuid>f425d1d4-c718-4de3-b0d7-d24c75feaa1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kishore K'])[2]/preceding::button[1]</value>
      <webElementGuid>61f14955-6451-4a8c-8b48-a4d74979db92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>63c64b86-8d5a-40f0-80d1-4dbf687a25ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'alertdialog-close' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>eb719927-dc1b-46f9-9508-8c1b36c29d7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
