<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__mat-select-arrow ng-tns-c121-2</name>
   <tag></tag>
   <elementGuidId>c7bfb540-be8f-4422-a9c2-18c6afc926a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-select-arrow.ng-tns-c121-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='logincountrycode']/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2624870d-8119-46c6-ae2a-cb7b97e1a4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-arrow ng-tns-c121-2</value>
      <webElementGuid>65f00982-9d52-4382-b80a-64205fd143bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logincountrycode&quot;)/div[@class=&quot;mat-select-trigger ng-tns-c121-2&quot;]/div[@class=&quot;mat-select-arrow-wrapper ng-tns-c121-2&quot;]/div[@class=&quot;mat-select-arrow ng-tns-c121-2&quot;]</value>
      <webElementGuid>8758c8c7-d689-4a21-af4a-a24366101bfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='logincountrycode']/div/div[2]/div</value>
      <webElementGuid>59bd4422-ef17-4b13-a00c-42eda46ac7c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-select/div/div[2]/div</value>
      <webElementGuid>a7bd6fb9-4d45-4560-b7b3-c0a81f0c4505</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
