<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__mat-select-arrow-wrapper ng-tns-c121-43</name>
   <tag></tag>
   <elementGuidId>6b779a6e-f90f-4625-a321-8a2e1b2a6b1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='mat-select-28']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-select-arrow-wrapper.ng-tns-c121-43</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1c4d4670-6d99-4066-87e7-c08a3820a6a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-arrow-wrapper ng-tns-c121-43</value>
      <webElementGuid>fe4b7d7b-6b92-4ba9-8480-bd8148bb3a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-28&quot;)/div[@class=&quot;mat-select-trigger ng-tns-c121-43&quot;]/div[@class=&quot;mat-select-arrow-wrapper ng-tns-c121-43&quot;]</value>
      <webElementGuid>cf557a21-92eb-4916-b73d-4e6005c83e2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-28']/div/div[2]</value>
      <webElementGuid>b1ec92fb-eaf8-4093-aaea-ba2193e5f30e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::div[14]</value>
      <webElementGuid>e8ef9e66-9be4-4301-9b22-7f5c0f6c1bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/preceding::div[5]</value>
      <webElementGuid>c31f88d2-1bb4-459b-a85e-7abe4f16568b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/mat-form-field/div/div/div[3]/mat-select/div/div[2]</value>
      <webElementGuid>bd03b732-7b47-45e1-8b9c-f79949514488</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
