<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__mat-select-arrow-wrapper ng-tns-c121-48</name>
   <tag></tag>
   <elementGuidId>7e67b2ce-5197-4c64-bddb-7589083f326d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='mat-select-28']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-select-arrow-wrapper.ng-tns-c121-48</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4c261ae7-4bb7-4ae3-bf27-264672571a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-arrow-wrapper ng-tns-c121-48</value>
      <webElementGuid>b2333fd0-9921-4c21-8a56-79611455230b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-28&quot;)/div[@class=&quot;mat-select-trigger ng-tns-c121-48&quot;]/div[@class=&quot;mat-select-arrow-wrapper ng-tns-c121-48&quot;]</value>
      <webElementGuid>8c886e3b-82a8-41b1-86b3-4e8d0cf25fde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-28']/div/div[2]</value>
      <webElementGuid>872c974e-b159-4051-b206-16e68e0b1e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::div[14]</value>
      <webElementGuid>4d11e727-12ef-49f5-aa92-7196c2a258dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/preceding::div[5]</value>
      <webElementGuid>ba0addaf-0678-4869-aa94-6590a73b8c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/mat-form-field/div/div/div[3]/mat-select/div/div[2]</value>
      <webElementGuid>a8c4d48e-31aa-4b0e-a9ae-fdc15afaa0fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
