<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Number of records per page_mat-select-a_ccebcf</name>
   <tag></tag>
   <elementGuidId>1df8b441-9a80-4c65-b642-0ae63cf7ac14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-select-arrow.ng-tns-c121-28</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='mat-select-20']/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>58c09da8-4ede-4391-a0ec-b72e30a5a763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-arrow ng-tns-c121-28</value>
      <webElementGuid>dd88909e-f213-4c42-98ef-494fd032951e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-20&quot;)/div[@class=&quot;mat-select-trigger ng-tns-c121-28&quot;]/div[@class=&quot;mat-select-arrow-wrapper ng-tns-c121-28&quot;]/div[@class=&quot;mat-select-arrow ng-tns-c121-28&quot;]</value>
      <webElementGuid>9b561d5f-43a4-4a37-a4ff-1c22d3e88820</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-20']/div/div[2]/div</value>
      <webElementGuid>4bc6f134-fa6a-448c-8265-3fc75d3e32a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/mat-select/div/div[2]/div</value>
      <webElementGuid>1e080979-403c-49a3-afa7-f8b26e54b0ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
