<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__mat-select-arrow-wrapper ng-tns-c121-41</name>
   <tag></tag>
   <elementGuidId>dcb6fca3-50f6-45e1-aafa-950239e8a5d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='mat-select-26']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-select-arrow-wrapper.ng-tns-c121-41</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>02146c48-27f8-4c97-b398-bc476aef3d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-arrow-wrapper ng-tns-c121-41</value>
      <webElementGuid>7cc5cef8-2dfc-4c5a-aa0f-c7d953771e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-26&quot;)/div[@class=&quot;mat-select-trigger ng-tns-c121-41&quot;]/div[@class=&quot;mat-select-arrow-wrapper ng-tns-c121-41&quot;]</value>
      <webElementGuid>82a3169b-ce53-4456-9ce2-377e04466a2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-26']/div/div[2]</value>
      <webElementGuid>a3b18049-f1c7-4d61-a0f9-f3a321cab401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::div[14]</value>
      <webElementGuid>a3a325cd-594d-4b57-acb8-96bbb55c4560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::div[5]</value>
      <webElementGuid>1d84db8e-6ded-4320-bd09-1bb9fba8cc00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/mat-form-field/div/div/div[3]/mat-select/div/div[2]</value>
      <webElementGuid>0c6fe8de-bc92-4307-9575-f0404069fd8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
