<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Quent</name>
   <tag></tag>
   <elementGuidId>825ae7de-06e7-4f6b-acc8-150c9a99df25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mat-option-text > div.mat-tooltip-trigger.usertrail-data</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-26']/span/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>03cc7aab-d731-495f-a837-02013f06f7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-tooltip-trigger usertrail-data</value>
      <webElementGuid>56429a1e-1ef1-4a1f-919f-65ae23f7cc48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cdk-describedby-message-33</value>
      <webElementGuid>09206aa7-b5a8-4c60-af56-3c34a78ecb53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quent</value>
      <webElementGuid>a3012c76-9e94-453c-914b-271513fd5603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-26&quot;)/span[@class=&quot;mat-option-text&quot;]/div[@class=&quot;mat-tooltip-trigger usertrail-data&quot;]</value>
      <webElementGuid>b78c20d6-45d8-4a71-b80c-472b6ef8b57f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-26']/span/div</value>
      <webElementGuid>fad785e1-79fe-4f82-b565-1333b0b6da85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--Select--'])[6]/following::div[2]</value>
      <webElementGuid>b5f68d64-5dfd-4c4c-8f64-828d647c0c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QT Interval:'])[1]/following::div[23]</value>
      <webElementGuid>adfda81c-1f5d-4347-9b98-bf56d7caf2d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laptop'])[1]/preceding::div[3]</value>
      <webElementGuid>580d1507-0b30-4a27-ba0c-509beabdbab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Predicate'])[2]/preceding::div[5]</value>
      <webElementGuid>86ab8139-2d5c-4780-bdf4-634e38f9e98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[2]/span/div</value>
      <webElementGuid>7998a707-5a4a-4d10-9731-ecb6f3bbbc91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Quent' or . = 'Quent')]</value>
      <webElementGuid>9832d0c0-2a5b-44b2-83fa-a5ff4a52ac7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
